name = "Natrium"
license = "MIT"
licenselink = "https://github.com/mobybit/hugo-natrium-theme/blob/master/LICENSE.md"
description = "Natrium minimal theme"
homepage = "https://github.com/mobybit/hugo-natrium-theme"
tags = ["blog"]
features = ["blog", "taxonomies", "privacy", "i18n"]
min_version = 0.14

[author]
  name = "Tim Krieger"
  homepage = "https://blog.mobybit.de"
  
[original]
  name = "Jonathan Rutheiser"
  homepage = "http://jrutheiser.com/"
  repo = "https://github.com/jrutheiser/hugo-lithium-theme"
