baseurl = "https://example.org/"
languageCode = "en-us"
title = "Natrium Theme"
theme = "hugo-natrium-theme"
preserveTaxonomyNames = true
rssLimit = 10

[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Categories"
    url = "/categories"

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
